version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "v3frocks"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q5lcap96wlgk"
s3_prefix = "v3frocks"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
